site_name: scyllaridae
site_url: https://lehigh-university-libraries.github.io/scyllaridae/

repo_url: https://github.com/lehigh-university-libraries/scyllaridae
edit_uri: "edit/main/docs/"

theme: material
plugins:
  - search
  - social
  - tags
  - mermaid2

nav:
  - Home: index.md
  - Getting Started:
      - Gather requirements: requirements.md
  - Documentation:
      - Configuration Reference: configuration.md
      - API Reference: api.md
      - Deployment Guide: deployment.md
      - Troubleshooting: troubleshooting.md
  - Creating a new microservice:
      - Derivatives:
          - Understanding Islandora Events: derivatives/events.md
          - Implement your derivative microservice: derivatives/create.md
          - Testing your derivative microservice: derivatives/test.md
          - Wire everything up: derivatives/config.md
      - Indexing:
          - Understanding Islandora Events: index/events.md
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
